import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'pt' | 'en';

const DICTIONARY: Record<AppLanguage, Record<string, string>> = {
  pt: {
    home: 'Início',
    products: 'Produtos',
    promotions: 'Promoções',
    cart: 'Carrinho',
    orders: 'Encomendas',
    profile: 'Perfil',
    sell: 'Vender na MiniStore AO',
    register: 'Registar',
    login: 'Iniciar sessão',
    logout: 'Sair',
    adminPanel: 'Painel Admin',
    heroTitle: 'Encontre os seus produtos favoritos',
    heroSubtitle: 'Pesquise ofertas em tecnologia, casa, beleza e muito mais.',
    searchPlaceholder: 'O que deseja comprar?',
    allCategories: 'Todas as categorias',
    search: 'Pesquisar',
    why: 'Por que MiniStore AO?',
    featured: 'Produtos em destaque',
    featuredSubtitle: 'Escolhas populares para compradores da MiniStore AO.',
    viewCatalog: 'Ver catálogo',
    loadingProducts: 'A carregar produtos...',
    apiEmpty: 'Ligue a API para ver os produtos cadastrados.',
    saveTitle: 'Inicie sessão para poupar',
    saveText: 'Guarde o carrinho, acompanhe encomendas e veja ofertas especiais para a sua conta.',
    signup: 'Registe-se',
    authLoginTitle: 'Iniciar sessão',
    authLoginSubtitle: 'Insira as suas credenciais para aceder à sua conta',
    authEmail: 'Email',
    authPassword: 'Palavra-passe',
    authForgotPassword: 'Esqueceu a palavra-passe?',
    authSigningIn: 'A entrar...',
    authNoAccount: 'Não tem uma conta?',
    authRegisterLink: 'Registe-se',
    authCreateAccountTitle: 'Criar conta',
    authCreateAccountSubtitle: 'Preencha os dados abaixo para criar a sua conta',
    authProfilePicture: 'Foto de Perfil',
    authFullName: 'Nome completo',
    authConfirmPassword: 'Confirmar palavra-passe',
    authAcceptTerms: 'Aceito os',
    authTermsOfService: 'Termos de Serviço',
    authPrivacyPolicy: 'Política de Privacidade',
    authAnd: 'e a',
    authCreatingAccount: 'A criar conta...',
    authCreateAccount: 'Criar conta',
    authAccountCreated: 'Conta criada com sucesso!',
    authAccountCreatedText: 'A sua conta foi registada. Já pode iniciar sessão na plataforma para começar a comprar.',
    authSignInHere: 'Iniciar Sessão',
    authAlreadyHaveAccount: 'Já tem uma conta?',
    authBackHome: 'Voltar à página inicial',
    profileMyProfile: 'O Meu Perfil',
    profileManageInfo: 'Gerencie as suas informações pessoais e preferências',
    profilePersonalData: 'Informações Pessoais',
    profileSaveChanges: 'Guardar Alterações',
    profilePasswordChange: 'Alterar Palavra-passe',
    authCurrentPassword: 'Palavra-passe Atual',
    authNewPassword: 'Nova Palavra-passe',
    authConfirmNewPassword: 'Confirmar Nova Palavra-passe',
    authChangingPassword: 'A alterar...',
    authChangePasswordButton: 'Alterar Palavra-passe',
    profilePreferences: 'Preferências',
    profileLanguage: 'Idioma',
    profilePreferredCurrency: 'Moeda Preferida',
    profileDarkMode: 'Modo Escuro',
    profileDarkModeDescription: 'Ativar interface em tons escuros',
    profileSavePreferences: 'Guardar Preferências',
    profilePreferencesSaved: 'Preferências guardadas!',
    profileUpdateSuccess: 'Perfil atualizado com sucesso!',
    profileUpdateError: 'Erro ao atualizar perfil.',
    profilePasswordMismatch: 'As novas palavras-passe não coincidem.',
    profilePasswordLength: 'A nova palavra-passe deve ter pelo menos 8 caracteres.',
    profilePasswordSuccess: 'Palavra-passe alterada com sucesso!',
    profilePasswordError: 'Palavra-passe atual incorreta.',
    logoutConfirm: 'Tem a certeza que deseja sair do sistema?',
    profilePersonalDataTab: 'Dados Pessoais',
    profileSecurityTab: 'Segurança',
    profilePreferencesTab: 'Preferências',
    profileAvatarInfo: 'Clique na imagem para alterar o seu avatar.',
    profileSaveNewPhoto: 'Guardar Nova Foto',
    footerSlogan: 'A melhor experiência de compra para o seu projeto académico. Simples, robusta e eficiente.',
    footerSystemStatus: 'Sistema Operativo',
    footerCurrency: 'Moeda: AOA (Kz)',
    footerRights: 'Todos os direitos reservados.',
    adminDashboardTitle: 'Painel de Administração',
    adminDashboardSubtitle: 'Visão geral do sistema MiniStore AO',
    adminLoadingMetrics: 'A carregar métricas...',
    adminOrders: 'Encomendas',
    adminRevenue: 'Receita Total',
    adminProducts: 'Produtos',
    adminUsers: 'Utilizadores',
    adminPendingOrders: 'Pendente',
    adminDeliveredOrders: 'Entregue',
    adminCategories: 'Categorias',
    adminQuickActions: 'Ações Rápidas',
    adminRecentOrders: 'Encomendas Recentes',
    adminSeeAll: 'Ver tudo →',
    adminNoOrders: 'Ainda não há encomendas.',
    adminStockLowTitle: 'Stock Baixo ⚠️',
    adminManage: 'Gerir →',
    adminAllProductsInStock: '✅ Todos os produtos têm stock suficiente.',
    adminOutOfStock: 'Sem Stock',
    adminStockUnits: ' unidades',
    breadcrumbHome: 'Início',
    breadcrumbCatalog: 'Catálogo',
    outOfStock: 'Sem Stock',
    inStock: 'Em Stock',
    quantity: 'Quantidade',
    totalLabel: 'Total:',
    addToCart: 'Adicionar ao Carrinho',
    productUnavailable: 'Produto indisponível',
    productAvailableInStore: 'Produto disponível na loja.',
    searchProducts: 'Pesquisar produtos...',
    recommended: 'Recomendado',
    priceLowToHigh: 'Preço: Do mais baixo ao mais alto',
    priceHighToLow: 'Preço: Do mais alto ao mais baixo',
    moreStock: 'Mais Stock',
    filters: 'Filtros',
    categories: 'Categorias',
    priceAoA: 'Preço (AOA)',
    minimum: 'Mínimo',
    maximum: 'Máximo',
    catalogError: 'Não foi possível carregar os produtos. Confirme se a API está ligada.',
    noProductsFound: 'Nenhum produto encontrado',
    tryDifferentFilters: 'Tente ajustar os filtros, limpar a categoria ou procurar outro termo.',
    clearAllFilters: 'Limpar todos os filtros',
    onlyAvailableStock: 'Apenas produtos com stock',
    applyFilters: 'Aplicar filtros',
    cartTitle: 'O seu carrinho',
    loadingCart: 'A carregar carrinho...',
    cartUnavailable: 'Carrinho indisponível',
    cartEmpty: 'O seu carrinho está vazio',
    exploreProducts: 'Explorar produtos',
    orderSummary: 'Resumo da encomenda',
    subtotal: 'Subtotal',
    taxes: 'Impostos (14%)',
    checkout: 'Finalizar compra',
    continueShopping: 'Continuar a comprar',
    cartAddSuccess: 'Produto adicionado ao carrinho.',
    cartAddLoginRequired: 'Inicie sessão para adicionar produtos ao carrinho.',
    cartLoadAuthError: 'Inicie sessão para ver o seu carrinho.',
    cartUpdateError: 'Não foi possível atualizar o carrinho.',
    cartRemoveError: 'Não foi possível remover o produto.',
    cartEmptyError: 'Carrinho vazio',
    cartCheckoutError: 'Não foi possível finalizar a compra.',
    stockAvailable: 'Stock disponível:',
    viewProducts: 'Ver produtos',
    ordersMyOrders: 'As minhas encomendas',
    ordersHistory: 'Histórico de encomendas',
    backToOrders: '← Voltar às encomendas',
    allOrders: 'Todas',
    pendingOrdersLabel: 'Pendente',
    confirmedOrdersLabel: 'Confirmada',
    statusProcessing: 'Em processamento',
    statusShipped: 'Enviada',
    deliveredOrdersLabel: 'Entregue',
    cancelledOrdersLabel: 'Cancelada',
    noOrdersFound: 'Nenhuma encomenda encontrada',
    ordersNoneYet: 'Ainda não realizou nenhuma compra.',
    ordersNoStatus: 'Sem encomendas com este estado',
    createdOn: 'Criado em',
    orderNumber: 'Encomenda #',
    viewDetails: 'Ver detalhes',
    pendingPaymentNotice: 'Aguardando confirmação de pagamento',
    invoice: 'Fatura',
    cancel: 'Cancelar',
    exportPdf: 'Exportar PDF',
    paymentCash: 'Dinheiro',
    paymentTransfer: 'Transferência bancária',
    paymentCard: 'Cartão',
    cancelOrderConfirm: 'Tem a certeza que pretende cancelar esta encomenda?',
    cancelOrderError: 'Erro ao cancelar a encomenda.',
    backToCatalog: '← Voltar ao Catálogo',
    pricePerUnit: 'por unidade',
    remove: 'Remover',
    orderSummaryHeading: 'Resumo do pedido',
    ordersNoOrdersFound: 'Ainda nao fez nenhuma compra',
    orderCreatedOn: 'Criado em',
    orderItemsLabel: 'Produtos',
    orderDetailsLabel: 'Detalhes',
    paymentMethodLabel: 'Método de Pagamento',
    notesLabel: 'Notas',
    orderItemsTitle: 'Itens da Encomenda',
    summaryTitle: 'Resumo',
    exportPdfButton: 'Exportar PDF',
    checkoutSuccessTitle: 'Compra Confirmada!',
    checkoutSuccessMessage: 'A sua encomenda foi criada com sucesso.',
    viewOrder: 'Ver Encomenda',
    orderHistory: 'Histórico de Encomendas',
    authForgotPasswordTitle: 'Recuperar Palavra-passe',
    authForgotPasswordDescription: 'Insira o seu email para receber instruções de recuperação',
    authEmailPlaceholder: 'seu@email.com',
    authSend: 'Enviar',
    authBackToLogin: 'Voltar ao login',
    authResetCode: 'Código de Recuperação',
    authResetPasswordLabel: 'Redefinir Palavra-passe',
    authProcessing: 'A processar...',
    homeFeatureTitle1: 'Fácil de usar',
    homeFeatureText1: 'Interface clara e navegação simples para comprar sem distrações.',
    homeFeatureTitle2: 'Segurança reforçada',
    homeFeatureText2: 'Protegemos os seus dados e pagamentos com os melhores padrões de segurança.',
    homeFeatureTitle3: 'Entrega confiável',
    homeFeatureText3: 'Logística otimizada para que receba os seus produtos diretamente em casa.',
    aboutTitle: 'Sobre a MiniStore AO',
    aboutIntro: 'A MiniStore AO foi criada para modernizar o comércio digital em Angola com foco em usabilidade e segurança.',
    aboutFeatureInnovationTitle: 'Inovação Angolana',
    aboutFeatureInnovationText: 'Nascemos da vontade de modernizar o comércio digital em Angola, unindo tecnologia de ponta com as necessidades locais.',
    aboutFeatureSecurityTitle: 'Segurança Garantida',
    aboutFeatureSecurityText: 'Implementamos os mais rigorosos padrões de segurança para garantir que cada transação e dado pessoal esteja protegido.',
    aboutFeatureDeliveryTitle: 'Entrega Eficiente',
    aboutFeatureDeliveryText: 'Uma rede logística otimizada para que os seus produtos cheguem à sua porta com rapidez e cuidado.',
    aboutMissionTitle: 'Nossa Missão',
    aboutMissionText1: 'Proporcionar aos angolanos uma forma simples e moderna de adquirir produtos de qualidade, sem as barreiras tradicionais do comércio eletrónico.',
    aboutMissionText2: 'Focamos na experiência do utilizador, desde o primeiro clique até à entrega final, garantindo que cada passo seja transparente e gratificante.',
    termsTitle: 'Termos e Condições',
    termsAcceptanceTitle: '1. Aceitação dos Termos',
    termsAcceptanceText: 'Ao aceder e utilizar a MiniStore AO, o utilizador concorda em cumprir e vincular-se aos seguintes termos e condições de uso. Estes termos aplicam-se a todos os visitantes, utilizadores e outros que acedam ao serviço.',
    termsUsageTitle: '2. Uso do Serviço',
    termsUsageText: 'A MiniStore AO é uma plataforma de e-commerce destinada à comercialização de produtos eletrónicos e outros. O utilizador compromete-se a utilizar o serviço de forma lícita, não praticando atos que possam danificar ou prejudicar a integridade do sistema.',
    termsAccountsTitle: '3. Contas de Utilizador',
    termsAccountsText: 'Ao criar uma conta connosco, deve fornecer informações precisas, completas e atuais. A falha em fazê-lo constitui uma violação dos Termos, o que pode resultar no encerramento imediato da sua conta no nosso serviço.',
    termsIntellectualTitle: '4. Propriedade Intelectual',
    termsIntellectualText: 'O serviço e o seu conteúdo original, funcionalidades e design são e permanecerão propriedade exclusiva da MiniStore AO e dos seus licenciadores.',
    termsChangesTitle: '5. Alterações aos Termos',
    termsChangesText: 'Reservamo-nos o direito, a nosso exclusivo critério, de modificar ou substituir estes Termos a qualquer momento. O que constitui uma alteração material será determinado a nosso exclusivo critério.',
    termsUpdated: 'Última atualização: 14 de Maio de 2026. Para dúvidas, contacte suporte@ministore.ao',
    privacyTitle: 'Política de Privacidade',
    privacyCollectionTitle: '1. Recolha de Dados',
    privacyCollectionText: 'A MiniStore AO recolhe informações pessoais que o utilizador nos fornece voluntariamente ao registar-se na nossa plataforma, tais como nome, email, endereço de entrega e dados de contacto.',
    privacyPurposeTitle: '2. Finalidade do Tratamento',
    privacyPurposeText: 'Os dados recolhidos destinam-se ao processamento de encomendas, gestão de conta de utilizador, apoio ao cliente e, caso autorizado, envio de comunicações de marketing.',
    privacyProtectionTitle: '3. Proteção de Dados',
    privacyProtectionText: 'Implementamos medidas de segurança técnicas e organizativas adequadas para proteger os seus dados pessoais contra a destruição acidental ou ilícita, a perda, a alteração e a difusão ou o acesso não autorizados.',
    privacyRightsTitle: '4. Direitos dos Utilizadores',
    privacyRightsText: 'O utilizador tem o direito de aceder, retificar, apagar ou limitar o tratamento dos seus dados pessoais. Pode exercer estes direitos através das definições de perfil ou contactando o nosso suporte.',
    privacyCookiesTitle: '5. Cookies',
    privacyCookiesText: 'Utilizamos cookies para melhorar a experiência de navegação e analisar o tráfego do site. Pode gerir as suas preferências de cookies nas definições do seu navegador.',
    privacyFooterNote: 'Esta política está em conformidade com as boas práticas de proteção de dados. MiniStore AO - Comprometidos com a sua privacidade.',
    footerExplore: 'Explorar',
    footerAccount: 'Minha Conta',
    footerAdministration: 'Administração',
    footerInstitutional: 'Institucional',
    footerCatalog: 'Catálogo de Produtos',
    footerPromotions: 'Promoções Ativas',
    footerNews: 'Novidades',
    footerBestsellers: 'Mais Vendidos',
    footerProfile: 'Meu Perfil',
    footerOrders: 'Minhas Encomendas',
    footerCart: 'Carrinho de Compras',
    footerAdminDashboard: 'Painel Geral',
    footerAdminStock: 'Gerir Stock',
    footerAdminCategories: 'Gestão de Categorias',
    footerAdminReports: 'Relatórios de Vendas',
    footerAbout: 'Sobre a MiniStore AO',
    footerTerms: 'Termos e Condições',
    footerPrivacy: 'Política de Privacidade',
    footerContacts: 'Contactos',
    footerCopyright: '© {{year}} MiniStore AO - ISPTEC Engenharia de Software II. Todos os direitos reservados.',
  },
  en: {
    home: 'Home',
    products: 'Products',
    promotions: 'Deals',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    sell: 'Sell on MiniStore AO',
    register: 'Register',
    login: 'Sign in',
    logout: 'Sign out',
    adminPanel: 'Admin Panel',
    heroTitle: 'Find your favorite products',
    heroSubtitle: 'Search deals in technology, fashion, home, beauty and much more.',
    searchPlaceholder: 'What do you want to buy?',
    allCategories: 'All categories',
    search: 'Search',
    why: 'Why MiniStore AO?',
    featured: 'Featured products',
    featuredSubtitle: 'Popular picks for MiniStore AO shoppers.',
    viewCatalog: 'View catalog',
    loadingProducts: 'Loading products...',
    apiEmpty: 'Connect the API to see registered products.',
    saveTitle: 'Sign in to save',
    saveText: 'Save your cart, track orders and see special offers for your account.',
    signup: 'Create account',
    authLoginTitle: 'Sign in',
    authLoginSubtitle: 'Enter your credentials to access your account',
    authEmail: 'Email',
    authPassword: 'Password',
    authForgotPassword: 'Forgot your password?',
    authSigningIn: 'Signing in...',
    authNoAccount: 'Don’t have an account?',
    authRegisterLink: 'Register',
    authCreateAccountTitle: 'Create account',
    authCreateAccountSubtitle: 'Fill in the fields below to create your account',
    authProfilePicture: 'Profile picture',
    authFullName: 'Full name',
    authConfirmPassword: 'Confirm password',
    authAcceptTerms: 'I accept the',
    authTermsOfService: 'Terms of Service',
    authPrivacyPolicy: 'Privacy Policy',
    authAnd: 'and',
    authCreatingAccount: 'Creating account...',
    authCreateAccount: 'Create account',
    authAccountCreated: 'Account created successfully!',
    authAccountCreatedText: 'Your account has been registered. You can now sign in to start shopping.',
    authSignInHere: 'Sign in',
    authAlreadyHaveAccount: 'Already have an account?',
    authBackHome: 'Back to home page',
    profileMyProfile: 'My Profile',
    profileManageInfo: 'Manage your personal information and preferences',
    profilePersonalData: 'Personal Information',
    profileSaveChanges: 'Save Changes',
    profilePasswordChange: 'Change Password',
    authCurrentPassword: 'Current password',
    authNewPassword: 'New password',
    authConfirmNewPassword: 'Confirm new password',
    authChangingPassword: 'Changing...',
    authChangePasswordButton: 'Change Password',
    profilePreferences: 'Preferences',
    profileLanguage: 'Language',
    profilePreferredCurrency: 'Preferred currency',
    profileDarkMode: 'Dark mode',
    profileDarkModeDescription: 'Enable dark themed interface',
    profileSavePreferences: 'Save Preferences',
    profilePreferencesSaved: 'Preferences saved!',
    profileUpdateSuccess: 'Profile updated successfully!',
    profileUpdateError: 'Error updating profile.',
    profilePasswordMismatch: 'New passwords do not match.',
    profilePasswordLength: 'The new password must be at least 8 characters long.',
    profilePasswordSuccess: 'Password changed successfully!',
    profilePasswordError: 'Current password is incorrect.',
    logoutConfirm: 'Are you sure you want to sign out?',
    profilePersonalDataTab: 'Personal Data',
    profileSecurityTab: 'Security',
    profilePreferencesTab: 'Preferences',
    profileAvatarInfo: 'Click the image to change your avatar.',
    profileSaveNewPhoto: 'Save New Photo',
    footerSlogan: 'The best shopping experience for your academic project. Simple, robust and efficient.',
    footerSystemStatus: 'Operating System',
    footerCurrency: 'Currency: AOA (Kz)',
    footerRights: 'All rights reserved.',
    adminDashboardTitle: 'Admin Dashboard',
    adminDashboardSubtitle: 'Overview of the MiniStore AO system',
    adminLoadingMetrics: 'Loading metrics...',
    adminOrders: 'Orders',
    adminRevenue: 'Total Revenue',
    adminProducts: 'Products',
    adminUsers: 'Users',
    adminPendingOrders: 'Pending',
    adminDeliveredOrders: 'Delivered',
    adminCategories: 'Categories',
    adminQuickActions: 'Quick Actions',
    adminRecentOrders: 'Recent Orders',
    adminSeeAll: 'View all →',
    adminNoOrders: 'No orders yet.',
    adminStockLowTitle: 'Low Stock ⚠️',
    adminManage: 'Manage →',
    adminAllProductsInStock: '✅ All products have sufficient stock.',
    adminOutOfStock: 'Out of Stock',
    adminStockUnits: ' units',
    breadcrumbHome: 'Home',
    breadcrumbCatalog: 'Catalog',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    quantity: 'Quantity',
    totalLabel: 'Total:',
    addToCart: 'Add to Cart',
    productUnavailable: 'Product unavailable',
    productAvailableInStore: 'Product available in the store.',
    searchProducts: 'Search products...',
    recommended: 'Recommended',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    moreStock: 'More Stock',
    filters: 'Filters',
    categories: 'Categories',
    priceAoA: 'Price (AOA)',
    minimum: 'Minimum',
    maximum: 'Maximum',
    catalogError: 'Could not load products. Please check if the API is running.',
    noProductsFound: 'No products found',
    tryDifferentFilters: 'Try adjusting the filters, clearing the category or searching a different term.',
    clearAllFilters: 'Clear all filters',
    onlyAvailableStock: 'Only products with stock',
    applyFilters: 'Apply Filters',
    cartTitle: 'Your cart',
    loadingCart: 'Loading cart...',
    cartUnavailable: 'Cart unavailable',
    cartEmpty: 'Your cart is empty',
    exploreProducts: 'Explore products',
    orderSummary: 'Order summary',
    subtotal: 'Subtotal',
    taxes: 'Taxes (14%)',
    checkout: 'Checkout',
    continueShopping: 'Continue shopping',
    cartAddSuccess: 'Product added to cart.',
    cartAddLoginRequired: 'Sign in to add products to cart.',
    cartLoadAuthError: 'Sign in to view your cart.',
    cartUpdateError: 'Could not update your cart.',
    cartRemoveError: 'Could not remove the item.',
    cartEmptyError: 'Cart is empty',
    cartCheckoutError: 'Could not complete checkout.',
    stockAvailable: 'Stock available:',
    viewProducts: 'View products',
    ordersMyOrders: 'My Orders',
    ordersHistory: 'Order history',
    backToOrders: '← Back to orders',
    allOrders: 'All',
    pendingOrdersLabel: 'Pending',
    confirmedOrdersLabel: 'Confirmed',
    statusProcessing: 'Processing',
    statusShipped: 'Shipped',
    deliveredOrdersLabel: 'Delivered',
    cancelledOrdersLabel: 'Cancelled',
    noOrdersFound: 'No order found',
    ordersNoneYet: 'You have not made any purchase yet.',
    ordersNoStatus: 'No orders with this status',
    createdOn: 'Created on',
    orderNumber: 'Order #',
    viewDetails: 'View details',
    pendingPaymentNotice: 'Awaiting payment confirmation',
    invoice: 'Invoice',
    cancel: 'Cancel',
    exportPdf: 'Export PDF',
    paymentCash: 'Cash',
    paymentTransfer: 'Bank transfer',
    paymentCard: 'Card',
    cancelOrderConfirm: 'Are you sure you want to cancel this order?',
    cancelOrderError: 'Error canceling the order.',
    backToCatalog: '← Back to Catalog',
    pricePerUnit: 'per unit',
    remove: 'Remove',
    orderSummaryHeading: 'Order summary',
    ordersNoOrdersFound: 'You have not made any purchases yet',
    orderCreatedOn: 'Created on',
    orderItemsLabel: 'Items',
    orderDetailsLabel: 'Details',
    paymentMethodLabel: 'Payment method',
    notesLabel: 'Notes',
    orderItemsTitle: 'Order Items',
    summaryTitle: 'Summary',
    exportPdfButton: 'Export PDF',
    checkoutSuccessTitle: 'Purchase Confirmed!',
    checkoutSuccessMessage: 'Your order has been created successfully.',
    viewOrder: 'View Order',
    orderHistory: 'Order History',
    authForgotPasswordTitle: 'Forgot Password',
    authForgotPasswordDescription: 'Enter your email to receive recovery instructions',
    authEmailPlaceholder: 'your@email.com',
    authSend: 'Send',
    authBackToLogin: 'Back to login',
    authResetCode: 'Recovery Code',
    authResetPasswordLabel: 'Reset Password',
    authProcessing: 'Processing...',
    homeFeatureTitle1: 'Easy to use',
    homeFeatureText1: 'Clear interface and simple navigation for distraction-free shopping.',
    homeFeatureTitle2: 'Enhanced security',
    homeFeatureText2: 'We protect your data and payments with top security standards.',
    homeFeatureTitle3: 'Reliable delivery',
    homeFeatureText3: 'Optimized logistics so your products arrive to your door quickly.',
    homeFeatureOffer: 'Offer',
    aboutTitle: 'About MiniStore AO',
    aboutIntro: 'MiniStore AO was created to modernize digital commerce in Angola with a strong focus on usability and security.',
    aboutFeatureInnovationTitle: 'Angolan Innovation',
    aboutFeatureInnovationText: 'We were born from the desire to modernize digital commerce in Angola by combining cutting-edge technology with local needs.',
    aboutFeatureSecurityTitle: 'Guaranteed Security',
    aboutFeatureSecurityText: 'We implement the strictest security standards to ensure every transaction and personal data is protected.',
    aboutFeatureDeliveryTitle: 'Efficient Delivery',
    aboutFeatureDeliveryText: 'An optimized logistics network so your products reach your door fast and with care.',
    aboutMissionTitle: 'Our Mission',
    aboutMissionText1: 'Provide Angolans with a simple, modern way to buy quality products without the traditional barriers of e-commerce.',
    aboutMissionText2: 'We focus on the user experience from the first click to final delivery, ensuring every step is transparent and rewarding.',
    termsTitle: 'Terms and Conditions',
    termsAcceptanceTitle: '1. Acceptance of Terms',
    termsAcceptanceText: 'By accessing and using MiniStore AO, the user agrees to comply with and be bound by these terms and conditions of use. These terms apply to all visitors, users and others who access the service.',
    termsUsageTitle: '2. Use of Service',
    termsUsageText: 'MiniStore AO is an e-commerce platform intended for the sale of electronics and other products. The user agrees to use the service lawfully and not engage in acts that may damage or harm the integrity of the system.',
    termsAccountsTitle: '3. User Accounts',
    termsAccountsText: 'When creating an account with us, you must provide accurate, complete and current information. Failure to do so constitutes a breach of the Terms, which may result in the immediate termination of your account.',
    termsIntellectualTitle: '4. Intellectual Property',
    termsIntellectualText: 'The service and its original content, features and design are and will remain the exclusive property of MiniStore AO and its licensors.',
    termsChangesTitle: '5. Changes to Terms',
    termsChangesText: 'We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.',
    termsUpdated: 'Last updated: May 14, 2026. For questions, contact support@ministore.ao',
    privacyTitle: 'Privacy Policy',
    privacyCollectionTitle: '1. Data Collection',
    privacyCollectionText: 'MiniStore AO collects personal information that the user provides voluntarily when registering on our platform, such as name, email, delivery address and contact details.',
    privacyPurposeTitle: '2. Purpose of Processing',
    privacyPurposeText: 'The collected data is used to process orders, manage user accounts, support customer service and, if authorized, send marketing communications.',
    privacyProtectionTitle: '3. Data Protection',
    privacyProtectionText: 'We implement appropriate technical and organizational security measures to protect your personal data against accidental or unlawful destruction, loss, alteration and unauthorized disclosure or access.',
    privacyRightsTitle: '4. User Rights',
    privacyRightsText: 'The user has the right to access, rectify, delete or restrict the processing of their personal data. You may exercise these rights via profile settings or by contacting our support.',
    privacyCookiesTitle: '5. Cookies',
    privacyCookiesText: 'We use cookies to improve browsing experience and analyze site traffic. You can manage your cookie preferences in your browser settings.',
    privacyFooterNote: 'This policy complies with data protection best practices. MiniStore AO - Committed to your privacy.',
    footerExplore: 'Explore',
    footerAccount: 'My Account',
    footerAdministration: 'Administration',
    footerInstitutional: 'Institutional',
    footerCatalog: 'Product Catalog',
    footerPromotions: 'Active Promotions',
    footerNews: 'News',
    footerBestsellers: 'Best Sellers',
    footerProfile: 'My Profile',
    footerOrders: 'My Orders',
    footerCart: 'Shopping Cart',
    footerAdminDashboard: 'Dashboard',
    footerAdminStock: 'Manage Stock',
    footerAdminCategories: 'Category Management',
    footerAdminReports: 'Sales Reports',
    footerAbout: 'About MiniStore AO',
    footerTerms: 'Terms and Conditions',
    footerPrivacy: 'Privacy Policy',
    footerContacts: 'Contacts',
    footerCopyright: '© {{year}} MiniStore AO - ISPTEC Software Engineering II. All rights reserved.',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly key = 'mini_ecommerce_language';
  private readonly languageSubject = new BehaviorSubject<AppLanguage>(this.initialLanguage());
  readonly language$ = this.languageSubject.asObservable();

  get language(): AppLanguage {
    return this.languageSubject.value;
  }

  setLanguage(language: AppLanguage): void {
    localStorage.setItem(this.key, language);
    this.languageSubject.next(language);
  }

  t(key: string): string {
    return DICTIONARY[this.language][key] ?? DICTIONARY.pt[key] ?? key;
  }

  text(pt?: string | null, en?: string | null, fallback = ''): string {
    if (this.language === 'en') {
      return en || pt || fallback;
    }
    return pt || en || fallback;
  }

  locale(): string {
    return this.language === 'en' ? 'en-US' : 'pt-PT';
  }

  private initialLanguage(): AppLanguage {
    const saved = localStorage.getItem(this.key);
    return saved === 'en' ? 'en' : 'pt';
  }
}
